### ISSUE TITLE
how about FPS when you test?

### ISSUE THREAD

**Issue by zhaokai5** [xuduo35/unet_mxnet2ncnn#4]
Hi, thanks for your sharing. I want to know how about the fps and hardware configure in your test, can you share this information. Thanks!

**Comment by xuduo35** [comment]
My local code got ~4 fps using two threads in mac pro 13inch with cpu '2.7 GHz Intel Core i5' for ~900k bytes model. It can run ~9 fps in iPhoneX because ncnn is optimized for mobile.
