### ISSUE TITLE
CPU Memory

### ISSUE THREAD

**Issue by Tomhouxin** [xuduo35/unet_mxnet2ncnn#5]
when run python trainunet.py. 
    File "/usr/local/lib/python3.4/dist-packages/mxnet/base.py", line 251, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [01:35:45] src/storage/./cpu_device_storage.h:73: Failed to allocate CPU Memory

**Comment by xuduo35** [comment]
How much batch size did you set?

**Comment by Tomhouxin** [comment]
16

**Comment by xuduo35** [comment]
16 is not big. But you can try to decrease it, or input image size. I don't remember if I met with this issue or not. But I'm using Python3.5 and mxnet-cu80. Which line of trainunet.py cause this crash?

**Comment by Tomhouxin** [comment]
I am also using Python3.5 on ubuntu14.04, not GPU. I can't remember which line. I'll let you know tomorrow.
I wonder  this is running on android

**Comment by xuduo35** [comment]
ncnn can run on android.

**Comment by Tomhouxin** [comment]
line 73，like ‘curr_loss = F.mean(loss).asscalar()’. ncnn can run on android, but trainunet ?

**Comment by xuduo35** [comment]
Seems your GPU's memory is not enough. You can try use small filter numbers. trainunet is only for training. Inference don't need these python scripts, only models.
