### ISSUE TITLE
代码中有个地方不是特别理解，特来请教一番。

### ISSUE THREAD

**Issue by q1vs5k5** [xuduo35/unet_mxnet2ncnn#7]
top = (INPUT_HEIGHT*top)/width;
bottom = (INPUT_HEIGHT*bottom)/width;
left = (INPUT_WIDTH*left)/height;
right = (INPUT_WIDTH*right)/height;
请教您一下，这四个变量这么定义有什么具体的意义吗？

**Comment by xuduo35** [comment]
之前训练模型的时候想不开，我做了等比例缩放。所以inference的时候，也做等比例缩放，计算边界用的，超出边界的填0。其实直接resize就好。

**Comment by q1vs5k5** [comment]
嗯嗯 知道了，多谢解惑！
