### ISSUE TITLE
is it possible to use this source code for unet-keras

### ISSUE THREAD

**Issue by nqthai309** [xuduo35/unet_mxnet2ncnn#9]
i have model trained UNET segmentation (keras), then converted to NCNN (param, bin) by tool keras2ncnn. Can i use this source code for my converted model? Thanks <3

**Comment by xuduo35** [comment]
This project is used to convert mxnet to ncnn. But it's too old. I think there is better choice. But if keras2ncnn works, why do you need other tool?

**Comment by nqthai309** [comment]
![image](https://user-images.githubusercontent.com/61822545/159521723-e6bffa37-3d38-4b01-9641-7c5e59678641.png)


i use keras2ncnn tool to convert my keras-unet model. However, in the ncnn source code there is no sample code to infer the unet-ncnn model. Do you have any suggestions for me to implement it? Thanks

**Comment by xuduo35** [comment]
You can refer to [https://github.com/xuduo35/unet_mxnet2ncnn/blob/master/ncnn-unet/src/main.cpp](url) for inference code.
